### ISSUE TITLE
Could not run kodi container on pure wayland machine

### ISSUE THREAD

**Issue by kanyck** [ehough/docker-kodi#26]
Trying to setup a HTPC. It's a fresh Void Linux install with wayland+weston+elogind on a spare NUC. (I want to add LMS there and probably some other stuff later on, that's why I did not used LibreELEC for this, which would be quite straightforward).
So, weston starts okay and seemingly works (didn't go beyond the successful start for I actually don't need it).
However I can't make the dockerized kodi start.
My most successful test setup so far was like this
`x11docker -- wayland -- tty --gpu --alsa --homedir /home/docker` 
which gets 
`invalid volume specification:  '/run/user/1000/:/:rw' invalid mount config for type "bind": destination can't be '/'.`
Adding` "-v /run/user/1000:/tmp:rw"` doesn't help.
XDG_RUNTIME_DIR is manually set and exported on a host machine.
I'm not quite familiar with docker yet so I probably would need some directions...
UPDATE: XDG_RUNTIME_DIR being unset makes the "/:/:rw" instead

**Comment by mviereck** [comment]
This is a bug in x11docker, not from the kodi image. I have fixed it in x11docker master branch, should work now. Please update and try out.

However, I doubt that kodi itself runs on Wayland, but I am not sure about that.

**Comment by kanyck** [comment]
@mviereck So I reported to the wrong place. Sorry for that.
Updated with x11docker --update-master, now on 6.0.0-beta. Still no change, I got the same error.
Kodi is claimed to run on Wayland. I always was curious to try...

**Comment by mviereck** [comment]
> So I reported to the wrong place. Sorry for that.

No problem. :-)

> Updated with x11docker --update-master, now on 6.0.0-beta. Still no change, I got the same error.

That's odd. Could you please open a ticket at https://github.com/mviereck/x11docker and attach the `x11docker.log` file?

>  Kodi is claimed to run on Wayland. I always was curious to try...

ok, I wasn't aware of that.

**Comment by ehough** [comment]
@mviereck Thanks, as always, for your help! As @kanyck pointed out, Kodi is indeed supposed to work via Wayland.

Closing this ticket as the issue is more with x11docker, but feel free to continue the discussion here.

**Comment by kanyck** [comment]
OK, closing it here. New issue is 
mviereck/x11docker#166

**Comment by mviereck** [comment]
On x11docker side the bug is basically fixed.
However, kodi fails with:
```
$ x11docker --wayland erichough/kodi

---> starting Kodi with command: kodi-standalone
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
/usr/bin/kodi --standalone  has exited in an unclean state 3 times in the last 0 seconds.
Something is probably wrong
---> Kodi does not appear to be running. Exiting.
```
Maybe there is a kodi Wayland library missing.

**Comment by mviereck** [comment]
I've added `RUN apt-get install -y kodi-gbm` and get a different message:
```
---> starting Kodi with command: kodi-standalone
ERROR: Unable to create GUI. Exiting

ERROR: Unable to create GUI. Exiting
ERROR: Unable to create GUI. Exiting
/usr/bin/kodi --standalone  has exited in an unclean state 3 times in the last 36 seconds.
Something is probably wrong
---> Kodi does not appear to be running. Exiting.
```
I am not sure how to proceed. Maybe kodi needs an option to be set to run on Wayland?

**Comment by p-hash** [comment]
Hi @mviereck 

GBM stands for **g**eneric **b**uffer **m**anager and `kodi-gbm` is there to run kodi standalone with neither xserver nor wayland present.

Adding `kodi-wayland` package to the image solved the issue for me.
